language: java

services:
 - cassandra

before_install: |-
 cqlsh -e "SOURCE 'crudmicroservices-middle/src/cassandra/cql/exec.cql';"

install: mvn -Denvironment=travis install -X

script: mvn test -X
jdk:
 - oraclejdk8

after_success:
 - mvn clean
