language: java

services:
 - cassandra

before_install: mvn -Denvironment=travis install -X

before_script:
 - cqlsh -f crudmicroservices-middle/src/cassandra/cql/load.cql

script: mvn test -X
jdk:
 - oraclejdk8

after_success:
 - mvn clean
